default:
  image: "archlinux:latest"

stages:
  - lint
  - build
  - test
  - publish

shellcheck:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm shellcheck
  script:
    find . -iname "*.sh" -exec shellcheck {} +

shfmt:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm shfmt
  script:
    find . -iname "*.sh" -exec shfmt -i 2 -ci -d {} +

yapf:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm yapf
  script:
    find . -iname "*.py" -exec python3 -m yapf -d {} +

flake8:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm flake8
  script:
    find . -iname "*.py" -exec python3 -m flake8 {} +

validate-packer:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm packer
  script:
    - packer validate -var "iso_checksum_url=https://mirror.pkgbuild.com/iso/latest/sha1sums.txt" -except=vagrant-cloud vagrant.json
    - packer validate local.json
    - packer validate cloud.json

build:qemu:
  stage: build
  tags:
    - secure-kvm
  before_script:
    - pacman -Syu --needed --noconfirm packer qemu-headless
  script:
    - packer build -parallel-builds=1 -var 'headless=true' -var 'write_zeroes=yes' -only=qemu local.json
  artifacts:
    name: "qemu"
    paths:
      - "Arch-Linux-x86_64-libvirt-*.box"
    expire_in: 2d
  resource_group: vm-build

build:virtualbox:
  stage: build
  tags:
    - secure-virtualbox
  before_script:
    - pacman -Syu --needed --noconfirm packer virtualbox
  script:
    - packer build -parallel-builds=1 -var 'headless=true' -var 'write_zeroes=yes' -only=virtualbox-iso local.json
  artifacts:
    name: "virtualbox"
    paths:
      - "Arch-Linux-x86_64-virtualbox-*.box"
    expire_in: 2d
  resource_group: vm-build

test-vbox-reflector:
  stage: test
  tags:
    - secure-virtualbox
  before_script:
    - pacman -Syu --needed --noconfirm virtualbox vagrant
  script:
    - vagrant box add Arch-Linux-x86_64-virtualbox-*.box --name archlinux --force
    - vagrant init archlinux
    - vagrant up --provider=virtualbox
    - vagrant ssh -c "cat /etc/pacman.d/mirrorlist" | grep Reflector
  resource_group: vm-build

test-qemu-reflector:
  stage: test
  tags:
    - secure-kvm
  before_script:
    - pacman -Syu --needed --noconfirm qemu-headless vagrant
    - systemctl start libvirtd.service
    - vagrant plugin install vagrant-libvirt
  script:
    - vagrant box add Arch-Linux-x86_64-libvirt-*.box --name archlinux --force
    - vagrant init archlinux
    - vagrant up --provider=libvirt
    - vagrant ssh -c "cat /etc/pacman.d/mirrorlist" | grep Reflector
  resource_group: vm-build

test-vbox-network:
  stage: test
  variables:
    VAGRANT_VAGRANTFILE: "network.Vagrantfile"
  tags:
    - secure-virtualbox
  before_script:
    - pacman -Syu --needed --noconfirm virtualbox vagrant
    - vagrant box add Arch-Linux-x86_64-virtualbox-*.box --name archlinux --force
    - cd test
  script:
    - vagrant up --provider=virtualbox
    - vagrant ssh -c "ip addr" | grep 192.168.0.42
  resource_group: vm-build

test-qemu-network:
  stage: test
  variables:
    VAGRANT_VAGRANTFILE: "network.Vagrantfile"
  tags:
    - secure-kvm
  before_script:
    - pacman -Syu --needed --noconfirm qemu-headless vagrant
    - vagrant plugin install vagrant-libvirt
    - vagrant box add Arch-Linux-x86_64-libvirt-*.box --name archlinux --force
    - cd test
  script:
    - vagrant up --provider=libvirt
    - vagrant ssh -c "ip addr" | grep 192.168.0.42
  resource_group: vm-build  

publish:
  stage: publish
  tags:
    - secure-kvm
    - secure-virtualbox
  before_script:
    - pacman -Syu --needed --noconfirm qemu-headless virtualbox packer
  script:
    - packer build -force -parallel-builds=1 -var "vagrant_cloud_token=$VAGRANT_API_TOKEN" -var 'headless=true' -var 'write_zeroes=yes' -except=vmware-iso vagrant.json
  only:
    refs:
      - release
    variables:
      - $SCHEDULED_PUBLISH == "TRUE"
  resource_group: vm-build
